name: deploy_prod
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: init ssh, deploy
        run: |
          eval $(ssh-agent -s)
          echo "${{secrets.PRIVATE_KEY}}" > deploy.key
          mkdir -p ~/.ssh
          chmod 0600 deploy.key
          ssh-add deploy.key
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh ${{secrets.HOST_NAME}}@${{secrets.BSC_PROD_HOST}} 'mkdir -p ~/githubActions/ede_stats/'
          scp sh/restart_prod.sh ${{secrets.HOST_NAME}}@${{secrets.BSC_PROD_HOST}}:~/githubActions/ede_stats/
          scp docker-compose_prod.yml ${{secrets.HOST_NAME}}@${{secrets.BSC_PROD_HOST}}:~/githubActions/ede_stats/
          ssh ${{secrets.HOST_NAME}}@${{secrets.BSC_PROD_HOST}} "cd ~/githubActions/ede_stats && sh restart_prod.sh"

